### ISSUE TITLE
Not building on Hackage

### ISSUE THREAD

**Issue by mitchellvitez** [zsedem/haskell-cpython#11]
Looks like we need to get some version of python into pkg-config for hackage builds to pass

https://hackage.haskell.org/package/cpython-3.5.0/reports/1

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: cpython-3.5.0 (user goal)
[__1] rejecting: cpython:-usepython38 (conflict: pkg-config package
python3-any, not found in the pkg-config database)
[__1] rejecting: cpython:+usepython38 (conflict: pkg-config package
python-3.8-any, not found in the pkg-config database)
[__1] fail (backjumping, conflict set: cpython, cpython:usepython38)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cpython, cpython:usepython38
```

**Comment by zsedem** [comment]
Are you saying that the project compile locally, but won't compile from hackage?

**Comment by zsedem** [comment]
Anyway, we can still have an ugly workaround to make cabal flags for every python minor version, which we want to support ...

**Comment by zsedem** [comment]
I just understood your concern. :smile: 

On hackage I do not expect it to compile, because it would need python for that, which means hackage build system would need some kind of mechanism for installing the pkg-config dependencies for that.

**Comment by mitchellvitez** [comment]
Ah, I didn't know enough about the hackage build system to know this wasn't possible. Closing this issue....

---
> Are you saying that the project compile locally, but won't compile from hackage?

This was also true for me today, causing some confusion. It was just because this repo is on 3.7.1 and the hackage version is still on 3.5.0. No real issue!

**Comment by zsedem** [comment]
I was thinking we can make a 4.0.0 after adding some better API s
